# Site settings
title: The Possibilities are Endless
header-img: img/home-bg.png
email: larasanders@gmail.com
copyright_name: lsivak
description: > # this means to ignore newlines until "baseurl:"
  Choose Your Own Adventure
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  lsivak
learn_profile: lsivak
email_username: larasanders@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
